default: &defaults
  docker:
    - image: circleci/cci-demo-docker-primary:0.0.2
  working_directory: ~/todobackend

cmd_install_dependencies: &cmd_install_docker-client
  - run:
      name: Install Docker client
      command: |
        set -x
        VER="17.03.0-ce"
        curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
        mv /tmp/docker/* /usr/bin

cmd_install_dependencies: &cmd_install_docker-compose
  - run:
      name: Install Docker Compose
      command: |
        set -x
        curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

cmd_attach_workspace: &cmd_attach_workspace
  attach_workspace:
    at: tmp/ 

version: 2
jobs:
  run_test:
    <<: *defaults
    steps:
      - checkout
      - *cmd_install_docker-client
      - *cmd_install_docker-compose
      - setup_remote_docker
      - run:
          name: Testing application
          command: make test
  
  build_artifacts:
    <<: *defaults
    steps:
      - checkout
      - *cmd_install_docker-client
      - *cmd_install_docker-compose
      - setup_remote_docker
      - run:
          name: Building application artifacts
          command: make build
  
  release_app:
    <<: *defaults
    steps:
      - checkout
      - *cmd_install_docker-client
      - *cmd_install_docker-compose
      - setup_remote_docker
      - run:
          name: Releasing application 
          command: make release


workflows:
  version: 2
  build_and_test:
    jobs:
      - run_test

      - build_artifacts:
          requires:
            - test
      - release_app:
          requires:
            - build
