version: 2
jobs:
  run_test:
    docker:
    - image: circleci/cci-demo-docker-primary:0.0.2
    working_directory: ~/todobackend
    attach_workspace:
    at: tmp/  

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - run:
          name: Testing application
          command: make test

      - run:
          name: Building application artifacts
          command: make build
  
      - run:
          name: Releasing application 
          command: make release
  

  build_image:
      docker:
      - image: ubuntu:16.04
      working_directory: ~/todobackend
      attach_workspace:
      at: tmp/  
      steps:
        - checkout
        - run:
            name: build final image
            command: bash .circleci/build.sh
                  
        - persist_to_workspace:
            root: workspace
            paths:
              - output
  
  deploy_app:
    docker:
    - image: ubuntu:16.04
    working_directory: ~/todobackend
    attach_workspace:
    at: tmp/  
    steps:
      - checkout
      - attach_workspace:
          at: ~/todobackend/workspace
      - deploy:
          name: Deploy service
          command: bash .circleci/deploy.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - run_test

      - build_image
      - deploy_app:
          requires:
            - run_test
            - build_image
      